-- AlterTable
ALTER TABLE "pace_record" ALTER COLUMN "distance" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "time" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pace" SET DATA TYPE DOUBLE PRECISION;
